#! /bin/bash
touch /home/therebelrobot/git/rain/beauty-of-the-night/public/css/main.less
sleep 5s
touch /home/therebelrobot/git/rain/beauty-of-the-night/public/css/main.less
sleep 5s
touch /home/therebelrobot/git/rain/beauty-of-the-night/public/css/main.less
sleep 5s
touch /home/therebelrobot/git/rain/beauty-of-the-night/public/css/main.less 
sleep 5s
touch /home/therebelrobot/git/rain/beauty-of-the-night/public/css/main.less 
sleep 5s
touch /home/therebelrobot/git/rain/beauty-of-the-night/public/css/main.less
sleep 5s
touch /home/therebelrobot/git/rain/beauty-of-the-night/public/css/main.less
sleep 5s
touch /home/therebelrobot/git/rain/beauty-of-the-night/public/css/main.less
sleep 5s
touch /home/therebelrobot/git/rain/beauty-of-the-night/public/css/main.less 
sleep 5s
touch /home/therebelrobot/git/rain/beauty-of-the-night/public/css/main.less 
sleep 5s
touch /home/therebelrobot/git/rain/beauty-of-the-night/public/css/main.less 
sleep 5s
touch /home/therebelrobot/git/rain/beauty-of-the-night/public/css/main.less 